POST http://localhost:8080/admin/medicines
Content-Type: application/json

{
  "name": "test name",
  "description": "test description",
  "price": 33.3
}

###
POST http://localhost:8080/admin/suppliers
Content-Type: application/json

{
  "name": "test supplier"
}

###
