POST http://localhost:8081/admin/medicines
Content-Type: application/json

{
  "name": "Tempalgin",
  "description": "Analgesic-antipyretic of a combined composition",
  "price": 110
}

###
POST http://localhost:8081/admin/medicines/change price
Content-Type: application/json

{
  "medicine": 1,
  "price": 120
}

###
