POST http://localhost:8081/admin/medicines
Content-Type: application/json

{
  "name": "Karvelis",
  "description": "good ",
  "price": 40
}

###
POST http://localhost:8081/admin/medicines/change price
Content-Type: application/json

{
  "medicine": 2,
  "price": 220
}

###
