GET http://localhost:8081/analyst/analyse/supply/stocks
Content-Type: application/json

{
  "date": "2022-12-01",
  "supply": 1
}

###
GET http://localhost:8081/analyst/analyse/supply/sales/date
Content-Type: application/json

{
  "date": "2022-12-01",
  "supply": 2
}

###
GET http://localhost:8081/analyst/analyse/supply/sales/period/
Content-Type: application/json

{
  "start": "2022-11-16",
  "end": "2022-11-27",
  "supply": 3
}

###
GET http://localhost:8081/analyst/analyse/supply/sales/month
Content-Type: application/json

{
  "date": "2022-11",
  "supply": 3
}




###
GET http://localhost:8081/analyst/analyse/medicine/sales/per day/
Content-Type: application/json

{
  "date": "2022-11-27",
  "medicine": 1
}

###
GET http://localhost:8081/analyst/analyse/medicine/sales/period/
Content-Type: application/json

{
  "start": "2022-11-17",
  "end": "2022-11-27",
  "medicine": 4
}

###
GET http://localhost:8081/analyst/analyse/medicine/sales/month/
Content-Type: application/json

{
  "date": "2022-11",
  "medicine": 4
}

###
GET http://localhost:8081/analyst/analyse/medicine/stock/
Content-Type: application/json

{
  "date": "2022-11-27",
  "medicine": 1
}

###
GET http://localhost:8081/analyst/analyse/medicine/sales/statistics/
Content-Type: application/json

{
  "start": "2022-11-24",
  "end": "2022-11-27",
  "medicine": 4
}


###
GET http://localhost:8081/analyst/analyse/medicine/distribution sales/
Content-Type: application/json

{
  "start": "2022-11-18",
  "end": "2022-11-27"
}

###
GET http://localhost:8081/analyst/analyse/profit and loss/date/
Content-Type: application/json

{
  "date": "2022-11-27"
}

###
GET http://localhost:8081/analyst/analyse/profit and loss/period/
Content-Type: application/json

{
  "start": "2022-11-01",
  "end": "2022-11-27"
}

###
GET http://localhost:8081/analyst/analyse/profit and loss/month/
Content-Type: application/json

{
  "date": "2022-11"
}

###
GET http://localhost:8081/analyst/analyse/average check/
Content-Type: application/json

{
  "start": "2022-11-17",
  "end": "2022-11-27"
}



