POST http://localhost:8081/supplier/registration
Content-Type: application/json

{
  "name": "Phfizer"
}

###
GET http://localhost:8081/supplier/medicines
Accept: application/json

###
POST http://localhost:8081/supplier/supply
Content-Type: application/json

{
  "supplierId": 3,
  "items": [
    {
      "medicineId": 4,
      "count": 5,
      "manufactureDate": "2021-10-01",
      "expirationDate": "2022-12-15",
      "pricePaidSupplier": 23
    },
    {
      "medicineId": 1,
      "count": 10,
      "manufactureDate": "2021-12-16",
      "expirationDate": "2022-12-15",
      "pricePaidSupplier": 12
    }

  ]
}

###

