POST http://localhost:8081/supplier/registration
Content-Type: application/json

{
  "name": "ALexion"
}

###

GET http://localhost:8081/supplier/medicines
Accept: application/json

###
POST http://localhost:8081/supplier/supply
Content-Type: application/json

{
  "supplierId": 3,
  "items": [
    {
      "medicineId": 4,
      "count": 4,
      "manufactureDate": "2021-10-01",
      "expirationDate": "2022-12-31",
      "pricePaidSupplier": 23
    },
    {
      "medicineId": 1,
      "count": 10,
      "manufactureDate": "2021-01-01",
      "expirationDate": "2022-11-29",
      "pricePaidSupplier": 12
    }

  ]
}

###

